<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Flaminco.MinimalMediatR" Version="2.1.8" />
	  <PackageReference Include="Flaminco.OperationResults" Version="1.0.0" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IdentityShield.Contracts\IdentityShield.Contracts.csproj" />
    <ProjectReference Include="..\IdentityShield.Domain\IdentityShield.Domain.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Using Include="Flaminco.OperationResults" />
		<Using Include="Microsoft.AspNetCore.Http" />
		<Using Include="Microsoft.AspNetCore.Mvc" />
		<Using Include="IdentityShield.Application.Shields" />
		<Using Include="IdentityShield.Domain.Constants" />
		<Using Include="IdentityShield.Application.Providers" />
	</ItemGroup>
	
</Project>
